//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectionsDatabaseEntities : DbContext
    {
        public CollectionsDatabaseEntities()
            : base("name=CollectionsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumCollectionSet> AlbumCollectionSet { get; set; }
        public virtual DbSet<AlbumSet> AlbumSet { get; set; }
        public virtual DbSet<AuthorSet> AuthorSet { get; set; }
        public virtual DbSet<CollectionRecordSet> CollectionRecordSet { get; set; }
        public virtual DbSet<FormatSet> FormatSet { get; set; }
        public virtual DbSet<GenreSet> GenreSet { get; set; }
    }
}
