//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectionsDatabaseEntities : DbContext
    {
        public CollectionsDatabaseEntities()
            : base("name=CollectionsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumCollectionSet> AlbumCollectionSets { get; set; }
        public virtual DbSet<AlbumSet> AlbumSets { get; set; }
        public virtual DbSet<AuthorSet> AuthorSets { get; set; }
        public virtual DbSet<CollectionRecordSet> CollectionRecordSets { get; set; }
        public virtual DbSet<FormatSet> FormatSets { get; set; }
        public virtual DbSet<GenreSet> GenreSets { get; set; }
    }
}
